spring.application.name=TicketRush-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=<your_password>

spring.jpa.hibernate.ddl-auto=update